#!/usr/bin/env python

""" Solution to "Even Fibonacci numbers", aka Problem 2

http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

n = 4000000  # 10 | 4000000

def calc_fib_num_v1(n):
    "Find a Fibonacci number using Binet's formula."
    
    phi = (1 + 5**.5)/2
    fib_nummber = (phi**n - (-phi)**(-n))/5**.5
    return int(fib_nummber)

def calc_fib_num_v2():
    "Fibonacci sequence generator."
    x, y = 0, 1
    while True:
        yield x
        x, y = y, x+y

def even(seq):
    "An even number generator for a given sequence."
    for number in seq:
        if not number % 2:
            yield number

def under_a_number(seq, n):
    "An generator for sequence and a number."
    for number in seq:
        if number > n:
            break
        yield number  

def sum_even_fib_nums_method_1(n):
    "Find the sum of even valued Fibonacci terms"
    return sum([calc_fib_num_v1(_) for _ in xrange(1,n) if calc_fib_num_v1(_) %  2 == 0])

def sum_even_fib_nums_method_2(n):
    "Find the sum of even valued Fibonacci terms"
    return sum(even(under_a_number(calc_fib_num_v2(), n)))

if __name__ == "__main__":
    print("The sum of the even-valued Fibonacci terms below {0} is {1}."
            .format(n, sum_even_fib_nums_method_2(n)))
