#!/usr/bin/env Rscript

# File description -------------------------------------------------------------
# Solutions to "Even Fibonacci numbers"
# Problem 2, http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
#    (The sum of even-valued terms of the sequences is 44)
#
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

# Setup ------------------------------------------------------------------------
rm(list=ls()) # Delete all variables

# List of packages for session
.packages = c("numbers") # Contains the Fibonacci sequence

# Install required CRAN packages (if not already installed)
.inst <- .packages %in% installed.packages()
if(length(.packages[!.inst]) > 0) install.packages(.packages[!.inst])

# Load packages into session 
lapply(.packages, require, character.only=TRUE)

cat("\014")  # Clear console

# Define functions
source("benchmark_method.r")

# Define variables
n_terms <- 10 # 10 | 4000000000

# A brute force method -----------------------------------------------------------
# NOTE: It would be terrible idea to brute force for a sequence of 4 million

# Create Fibonacci sequence
fib_seq <- numeric(n_terms)
fib_seq[1] <- 1
fib_seq[2] <- 2
for (i in 3:n_terms) { 
  fib_seq[i] <- fib_seq[i-1] + fib_seq[i-2]
} 

# Get selected sums of within Fibonacci sequence
even_fib_method_1 <- function(n_terms){
  sum_even_fib <- 0 
  for (i in 1:length(fib_seq)) {
    if (fib_seq[i] %% 2 == 0) {
      sum_even_fib <- sum_even_fib + fib_seq[i]
    }
  }
  return(sum_even_fib)
}

# Get results
sum_method_1 <- even_fib_method_1(n_terms) 
# Benchmark method
benchmark_method(method_number=1, 
                 method_function=even_fib_method_1,
                 method_argument=n_terms) 

# Another brute force method ---------------------------------------------------
counter <- 1
sum_even_fib <- 0
previous_fib <- 0
current_fib <- 1

even_fib_method_2 <- function(n_terms){
  while (TRUE) {
    # Update Fibonacci
    old_current <- current_fib
    current_fib <- previous_fib + current_fib
    previous_fib <- old_current
    
    # Test how many terms
    if (counter >= n_terms) {
      break
    } else {
      counter <- counter +1 
    }
    
    # Update running total
    if (current_fib %% 2 == 0) sum_even_fib = sum_even_fib + current_fib
  }
  return(sum_even_fib)
}

# Get results
sum_method_2 <- even_fib_method_2(n_terms)
# Benchmark method
benchmark_method(method_number=2, 
                 method_function=even_fib_method_2,
                 method_argument=n_terms) 

# A vectorized method ----------------------------------------------------------
# Define a Fibonacci sequence
fib_seq <- fibonacci(n_terms, sequence = TRUE)

even_fib_method_3 <- function(fib_seq){
  # Sum even-valued terms of the sequence
  sum_even_fibo <- sum(fib_seq[fib_seq %% 2 == 0])
  return(sum_even_fibo)
}

# Get results
sum_method_3 <- even_fib_method_3(fib_seq)
# Benchmark method
benchmark_method(method_number=3, 
                 method_function=even_fib_method_3,
                 method_argument=fib_seq) 

# Write out results ------------------------------------------------------------
results_from_all_methods <- c(sum_method_1,
                              sum_method_2,
                              sum_method_3)

if (length(unique(results_from_all_methods)) == 1) {
  results_final <- sample(results_from_all_methods, size=1)
  cat("\nThe sum of the even-valued terms in a Fibonacci sequence below ",
      n_terms, " is ", results_final, ".\n\n", sep="")
} else {
  stop("Check methods")
}

# => 4613732